### ISSUE TITLE
3 strange code fragments

### ISSUE THREAD

**Issue by mjunix** [FreeCol/freecol#103]
(I don't have any experience with this codebase so maybe these are not bugs.)

1. https://github.com/FreeCol/freecol/blob/ef483bd4d41b4076f6a595adb52cbfe139419d81/src/net/sf/freecol/client/control/InGameController.java#L975
The formatting is strange, the if-statement start on same line as a closing brace, is an `else` missing before the `if`? If no `else` is missing then the if-statement should probably moved to a line of its own.
2. https://github.com/FreeCol/freecol/blob/ef483bd4d41b4076f6a595adb52cbfe139419d81/src/net/sf/freecol/server/ai/ColonyPlan.java#L1054-L1060
The two if-statements have the same condition.
3. https://github.com/FreeCol/freecol/blob/ef483bd4d41b4076f6a595adb52cbfe139419d81/src/net/sf/freecol/client/gui/mapviewer/MapViewer.java#L496
Identical expressions (`tcb.getBottomRightDirtyTile().getY()`) on both sides of subtraction operator.

**Comment by mpope042** [comment]
Correct on all counts I think.  #1 is a typo/omission, #2 is a logic error (long time since I wrote that code, glad I put a comment above), and #3 looks like the second getY is on the wrong corner of the box.  All three are fixed in commits 56e3d260, 4b418cd2, 5c4bafb9 respectively (note: sourceforge git repository commits, SF is the freecol development master, github merely contains a mirror, please prefer the SF bug tracker for further such issues).
