### ISSUE TITLE
Indian settlements become unknown after treaty merger of 2 AI players 

### ISSUE THREAD

**Issue by Qmass1** [FreeCol/freecol#19]
As the title says, even though they were all visited by scouts ages ago and trading was taking place most have become unkown. There are many more bugs than 11.7 had. Movement is broken for ships and is more complicated for land units sometimes units will move one square and then you will have to tell them again to move, very tedious. village names do not always link in turn report. I don't even know why you changed anything regards all these as they were all working well or at least better, the elephant in the room that needed/needs working on is the AI, it's not violent enough and cannot run the towns economies as you always see when you conquer one, that is what needed focusing on otherwise you're just polishing a turd.

**Comment by mpope042** [comment]
1. I can not reproduce the problem in the title.  The problem may have been caused by an earlier crash, but without a saved game that exhibits the problem we are in the dark.
2. "Movement is broken for ships"  Detail please!
3. Village names not linking?  Detail please!  We can not see what is happening on your screen or read your mind.
4. "Why did you change it?"  Err, because we needed to do a major rewrite to get around a bug that was totally wrecking games.
5. The AI.  Trust me we know.  There are several more specific bug reports open on the main bug tracker, but the AI is the least tractable part of the game.

This report is more a rant than anything actionable.  Only the title issue is specific enough to check further, so I intend to hunt through some more pre-Spanish-succession saved games and see if I can provoke a repeatable bug.  Otherwise expect no further action from the developers here unless clarification is provided.

**Comment by mpope042** [comment]
No response.  Closing.
