### ISSUE TITLE
General Feedback and Rant

### ISSUE THREAD

**Issue by cawoodm** [FreeCol/freecol#24]
As a long time player and fan of the original Colonization from 1995 I have the following feedback about freecol. In general the game shows much promise but is let down by a few basic things which I'm surprised aren't killing the fun for other players.

1. In general moving and selecting is a nightmare. Very often the goto function (be it "G" or by rightclicking a square) is buggy. It quite often moves a piece which is not selected. Or, you think it's selected (piece is displayed in bottom right of screen) but some other piece is actually selected. Try dragging a piece and it sometimes moves and sometimes you move some other piece:
![image](https://user-images.githubusercontent.com/498834/42381976-1e2f6ea0-8133-11e8-9cd7-35deef4a15a8.png)
In general selecting a unit is anywhere from frustrating to impossible:
 click unit, nothing happens. Click next to unit, area is selected in green. click unit nothing happens. click another area nothing happens...

2. Please flash the player selected. And make left-clicking only select units not terrain.

3. The tax rate is waaaay higher than the original game. By a factor of 10 or more I would say it grows without bounds. 1594 22% - 1599 27% - 1603 32%

4. Quality of immigrants waaay lower than in the original game.

5. Way fewer indian villages. In the screenshot above, in an area of about 100 squares there is 1 village. Also that village teaches Sugar planter but no land suitable for sugar is to be found anywhere here.

6. The Boycott message is misleading. It doesn't inform the player that rejecting the tax will result in goods being destroyed. A new player might think: hmmm, since I don't trade in Tools I can suffer a boycott. They will lose their tools.

7. There seems to be no production bonus for roads. In the original game, roads offer a +1 production bonus on all resources.

8. My town was 99% of the way to producing a cathedral. Next turn I was warned my town was producing nothing. The build queue was now empty, no cathedral to be seen anywhere. Bug.

9. I have a town producing 15 liberty bells with a printing press and it has 0% rebel sentiment.

**Comment by cawoodm** [comment]
A case in point:
![image](https://user-images.githubusercontent.com/498834/42382389-6c6c3fa2-8134-11e8-938e-f115b4b5c966.png)

Here I apparently have a colonist who can move - but where o where is he? Clicking/double-clicking on the bottom right does nothing. Only when I press an arrow key does he appear inside a flashing green square. If I click anywhere else, there is no way to re-select this colonist as he is on a village.

**Comment by mpope042** [comment]
1+2. There have been several recent bug fixes to unit selection and movement recently.
3+4. These are unsupported quantitative assertions.  We get a lot of them.  Too often these turn out to be due to mistaken memories.  What is needed are real numbers from experimenting with Col1.
5. The amount of native settlements is configurable... partly because of multiple contradictory claims about the them.  I am not saying you are wrong, but I am saying that we have other people disagreeing.  See #3+4 above.
6. I understand it was like this in Col1, but suggested improvements are of interest.
7. This is outright wrong.  FreeCol implements a production bonus for roads, and people have put in a lot of effort comparing the Col1 production.  You will need to provide a detailed example of where we are wrong to be convincing here.
8+9. Please consider opening a [http://sourceforge.net/p/freecol/bugs/](bug report), with the saved game from the turn before so we can reproduce the problem.

Ranting may be feel good, but there is so little here that is helpful or productive.
