### ISSUE TITLE
Bump version to 0.12

### ISSUE THREAD

**Issue by paulvi** [FreeCol/freecol#28]
There seems to be many places that have "0.11.6" 
 including  About dialogue and title.
Are there any reason not bump version to 0.12 as those nighy builds?

Is there script for setting version?

**Comment by Calebrw** [comment]
Originally on the SourceForge side, the move to either 0.11.7 or 0.12.0 would signal an actual release with install files built, etc. In the FreeCol development the move from 0.11.x to 0.12.x signifies a change to the save file so that 0.10.x files are no longer able to be opened by 0.12.x. Development has stagnated somewhat in the past year or so and as far as I know, nothing has changed that would warrant 0.12.0.

**Comment by paulvi** [comment]
Well, if and when 0.12 is released it should be named 0.12

so bumping to 0.12 and making sure it works as 0.12 is something holding 0.12 release ....

**Comment by mpope042** [comment]
The next FreeCol release will be 0.12.0 due to some major changes.  Development alas was stalled in 2019 but is picking up again now.  The last thing that is changed before release is the version number, so bumping it now would be premature.

**Comment by genodeftest** [comment]
It would be nice to have some new release that is closer to the current development. Are there plans to release an update any time soon?
