### ISSUE TITLE
Performance in Ubuntu desktop (GNOME 3)

### ISSUE THREAD

**Issue by paulvi** [FreeCol/freecol#84]
I have double boot system Windows 10 / Linux Ubuntu 18.04 LTS.
And while within Windows 10 performance is good, when booting in Ubuntu the performance is noticeably worse.

1. General responsiveness
While on Windows the time between key press or mouse command is almost not felt, I would save on Linux Ubuntu it is noticeable and sometime unpleasantly big 0.5s and more.
2. Invisible windows (sometimes, rarely but not always new dialog windows that are to appear, e.g. meeting natives, are not visible but switching with alt+tab to other app and switching with alt+tab back will bring on the screen)
3. Game sometimes is even becomes unresponsive, see #77

The problem maybe not directly because of this codebase, but I guess the situation should be at least known and documented.

Tech details
Linux Ubuntu 18.04 LTS (GNOME 3)
intel CPU 
16GB RAM
nVIDIA video card
Java 8

**Comment by mpope042** [comment]
Thanks for the report, and the Tech details, but alas, you left out the critiical one:  Which version of FreeCol are you using?

If it is the Ubuntu-packaged 0.11.6, please consider trying something more recent, like a [nightly release](https://github.com/FreeCol/freecol/releases).  This will very likely fix issue #2 as the code there has changed massively since 0.11.6.  Note that you may need a Java upgrade now or in the near future (Java 11 is the next LTS, 17 also has been seen working, not sure which ones are available for 18.04 right now).

Believe me we know about the graphic responsiveness issues.  There are several reasons why you may be having trouble. 
There was a major improvement quite recently on some platforms due to some excess drawing.  There are also intractable weird cases involving interactions between java and the nvidia drivers that are nothing to do with our codebase, but can occasionally be kicked with the user preferences (use pixmaps, use opengl, use xrender), which date back decades and regularly pop up on the sourceforge bug and discussion forums.

**Comment by mpope042** [comment]
Responsiveness has been much improved in the new release 0.12.0.  Closing.
